lecture13/serverspecディレクトリチェック

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -60,11 +60,25 @@ jobs:
           name: List directory to debug
           command: ls -la
       - run:
+          name: Check for Gemfile
+          command: |
+            if [ ! -f serverspec/Gemfile ]; then
+              echo "Gemfile not found!"
+              exit 1
+            fi
+      - run:
+          name: Install Bundler
+          command: gem install bundler
+      - run:
+          name: Configure Bundler Path
+          command: |
+            cd serverspec
+            bundle config set --local path 'vendor/bundle'
+      - run:
           name: bundle install
           command: |
             cd serverspec
-            gem list -e rails
-            bundle install --path vendor/bundle
+            bundle install
       - run:
           name: execute
           command: |
